// "The corpus in numbers" table in kb/README.md, generated by scripts/build-review.mjs
// between the START and END markers so the counts can't drift from sources.json.
import { TOOL_ONLY_LICENSES } from "./review.mjs";

export const START = "<!-- corpus-numbers:start (generated by scripts/build-review.mjs; do not edit by hand) -->";
export const END = "<!-- corpus-numbers:end -->";

const pct = (n, total) => `${Math.round((100 * n) / total)}%`;

/** reviewed: sources.json rows merged with reviewSource(). Returns the markdown between the markers. */
export function renderCorpusNumbers(reviewed, categoryCount, checkedAt) {
  const n = (f) => reviewed.filter(f).length;
  const total = reviewed.length;
  const permissive = n((r) => r.risk === "low");
  const rows = [
    [
      "Permissive licence (MIT, Apache, BSD, ISC, CC0, OFL…)",
      `${permissive} (${pct(permissive, total)})`,
      "Most of what we need can go straight into the game",
    ],
    ["No licence at all", n((r) => r.license === "none"), "Read-only: all rights reserved by default"],
    [
      "GitHub couldn't classify the licence",
      n((r) => r.license === "NOASSERTION"),
      "We read the LICENSE file for the ones that matter; the rest need a look before use",
    ],
    ["GPL / AGPL", n((r) => TOOL_ONLY_LICENSES.has(r.license)), "Tools and services to run, never code to bundle"],
    ["Under 100 stars", n((r) => r.stars < 100), "Unproven; mostly gap-fillers, Jev and API entries"],
    ["10k stars or more", n((r) => r.stars >= 10000), "The mature core of the stack"],
    ["Archived or stale", n((r) => r.archived || r.stale), "Reference only"],
    [
      'Marked "verify" or "unverified" in the notes',
      n((r) => /\bverify\b|unverified/i.test(r.note ?? "")),
      "Model licences, pricing pages that wouldn't load, and licences stated only in a README",
    ],
    ["Verdict: Adopt", n((r) => r.verdict.startsWith("Adopt")), "The recommended pick for each job"],
    [
      "Verdict: Avoid / Prototype only",
      n((r) => r.verdict === "Avoid" || r.verdict === "Prototype only"),
      "Region-locked or non-commercial models, data dumps, and archives of unclear provenance",
    ],
  ];
  return [
    START,
    `${total} sources in ${categoryCount} categories, checked against GitHub on ${checkedAt}.`,
    "",
    "| | Count | What it tells us |",
    "|---|---:|---|",
    ...rows.map(([what, count, why]) => `| ${what} | ${count} | ${why} |`),
    END,
  ].join("\n");
}

/** Replace the marked block in a document; throws if the markers are missing. */
export function replaceBlock(doc, block) {
  const from = doc.indexOf(START);
  const to = doc.indexOf(END);
  if (from < 0 || to < from) throw new Error(`markers not found: add ${START} ... ${END}`);
  return doc.slice(0, from) + block + doc.slice(to + END.length);
}
