#!/usr/bin/env node
// Regenerate INDEX.md and catalog/<category>.md from sources.json, after
// validating it. sources.json is the single source of truth: edit it, then run
//   node scripts/build-index.mjs
// `--check` exits non-zero if the generated files are out of date (for CI).

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { validateSources } from "./lib/validate.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const data = JSON.parse(readFileSync(join(root, "sources.json"), "utf8"));
const { categories, sources, checkedAt } = data;
const check = process.argv.includes("--check");

// --- validate -------------------------------------------------------------
const errors = validateSources(data);
if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

// --- render ---------------------------------------------------------------
const fmtStars = (n) => (n >= 1000 ? `${(n / 1000).toFixed(n >= 100000 ? 0 : 1)}k` : String(n));
const cell = (t) => String(t).replaceAll("|", "\\|").replaceAll("\n", " ");
const licenseCell = (l) =>
  l === "none" ? "⚠️ none (all rights reserved — reference only)" : l === "NOASSERTION" ? "⚠️ custom — read it" : l;

function table(rows) {
  const out = ["| Repo | ★ | License | What it is | What we take from it | Sync |", "|---|---:|---|---|---|---|"];
  for (const s of [...rows].sort((a, b) => b.stars - a.stars)) {
    const flags = [s.archived && "archived", s.stale && "stale"].filter(Boolean).join(", ");
    out.push(
      `| [${s.repo}](https://github.com/${s.repo})${flags ? ` _(${flags})_` : ""} | ${fmtStars(s.stars)} | ${cell(licenseCell(s.license))} | ${cell(s.what)} | ${cell(s.use)}${s.note ? ` — _${cell(s.note)}_` : ""} | ${s.sync} |`,
    );
  }
  return out.join("\n");
}

const header = "<!-- Generated by scripts/build-index.mjs from sources.json. Do not edit by hand. -->\n\n";
const files = new Map();

for (const c of categories) {
  const rows = sources.filter((s) => s.category === c.id);
  const groups = [...new Set(rows.map((s) => s.group ?? ""))];
  const body = groups.map((g) => `${g ? `### ${g}\n\n` : ""}${table(rows.filter((s) => (s.group ?? "") === g))}`).join("\n\n");
  files.set(
    `catalog/${c.id}.md`,
    `${header}# ${c.title}\n\n${c.description}\n\nStars checked ${checkedAt}. Notes: [notes/${c.id}.md](../notes/${c.id}.md). Sync locally: \`node scripts/sync.mjs --category ${c.id}\`\n\n${body}\n`,
  );
}

const summary = categories
  .map((c) => {
    const n = sources.filter((s) => s.category === c.id).length;
    return `| [${c.title}](catalog/${c.id}.md) | ${n} | ${cell(c.description)} |`;
  })
  .join("\n");
files.set(
  "INDEX.md",
  `${header}# Index\n\n${sources.length} source repos across ${categories.length} categories. Stars checked ${checkedAt}. For the analysis (stack, features, pipelines, policy) start at [kb/README.md](kb/README.md); for verdicts see [REVIEW.md](REVIEW.md).\n\n| Category | Repos | Covers |\n|---|---:|---|\n${summary}\n`,
);

let stale = 0;
for (const [rel, content] of files) {
  const path = join(root, rel);
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === content) continue;
  stale++;
  if (check) console.error(`out of date: ${rel}`);
  else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`wrote ${rel}`);
  }
}
if (check && stale) process.exit(1);
if (!stale) console.log("index up to date");
