#!/usr/bin/env node
// Generate REVIEW.md: one verdict and short review per source in sources.json.
//   node scripts/build-review.mjs          write REVIEW.md
//   node scripts/build-review.mjs --check  exit 1 if REVIEW.md is out of date
//
// Verdict logic lives in scripts/lib/review.mjs (shared with the MCP server):
// explicit picks from notes/*.md, then rules on licence, status and stars.
// Change a verdict there, not in REVIEW.md.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { categories, sources, checkedAt } = JSON.parse(readFileSync(join(root, "sources.json"), "utf8"));

import { ORDER, reviewSource } from "./lib/review.mjs";

const cell = (t) => String(t).replaceAll("|", "\\|").replaceAll("\n", " ");
const fmtStars = (n) => (n >= 1000 ? `${(n / 1000).toFixed(n >= 100000 ? 0 : 1)}k` : String(n));

const reviewed = sources.map((s) => ({ ...s, ...reviewSource(s) }));
const count = (rows) => Object.fromEntries(ORDER.map((v) => [v, rows.filter((r) => r.verdict === v).length]));

let md = `<!-- Generated by scripts/build-review.mjs from sources.json. Do not edit by hand; change verdicts in the script. -->

# Review: every source, one verdict

${reviewed.length} entries across ${categories.length} categories, reviewed ${checkedAt}. Each row gives a verdict, licence risk and a short review: what it is, what we'd use it for, and any caveat. Full details are in [\`catalog/\`](catalog/), and the reasoning behind the picks is in [\`notes/\`](notes/).

**How this was reviewed:** from the catalog data (stars, licence and status checked against GitHub on ${checkedAt}), the provider terms recorded in the notes column, and the recommendations in \`notes/*.md\`. **Nothing here has been installed or tested.** Verdicts are desk reviews to decide what to try first.

## Verdicts

| Verdict | Meaning |
|---|---|
| **Adopt** | Recommended pick for its job; start here |
| **Adopt (tool)** | Recommended, but copyleft: run it as a tool, never bundle it into the game |
| **Trial** | Permissive and relevant; try it when the need comes up |
| **Tool only** | GPL/AGPL: fine to run as a separate tool or service; don't copy or link its code |
| **Reference** | Read and learn from it: no licence, archived, or not something we'd install |
| **Prototype only** | Non-commercial or research-only weights: never ship its output |
| **Avoid** | Legal, ethical or provenance problem for this project |

Licence risk: **low** = permissive · **medium** = weak copyleft or source-available · **high** = GPL/AGPL or no licence · **check** = GitHub couldn't classify it, so read the LICENSE file.

## Summary

| Category | ${ORDER.join(" | ")} | Total |
|---|${ORDER.map(() => "---:").join("|")}|---:|
`;
for (const c of categories) {
  const rows = reviewed.filter((r) => r.category === c.id);
  const k = count(rows);
  md += `| [${c.title}](#${c.id}) | ${ORDER.map((v) => k[v] || "").join(" | ")} | ${rows.length} |\n`;
}
const all = count(reviewed);
md += `| **All** | ${ORDER.map((v) => `**${all[v]}**`).join(" | ")} | **${reviewed.length}** |\n`;

md += `\n## Avoid and prototype-only\n\n`;
for (const r of reviewed.filter((x) => x.verdict === "Avoid" || x.verdict === "Prototype only")) {
  md += `- **${r.verdict}:** [${r.repo}](https://github.com/${r.repo}): ${r.reasons[0]}.\n`;
}

for (const c of categories) {
  const rows = reviewed
    .filter((r) => r.category === c.id)
    .sort((a, b) => ORDER.indexOf(a.verdict) - ORDER.indexOf(b.verdict) || b.stars - a.stars);
  md += `\n<a id="${c.id}"></a>\n## ${c.title}\n\n${c.description} Notes: [notes/${c.id}.md](notes/${c.id}.md).\n\n`;
  md += `| Repo | Verdict | ★ | Licence risk | Review |\n|---|---|---:|---|---|\n`;
  for (const r of rows) {
    const extra = r.reasons.length ? ` **Caveat:** ${r.reasons.join("; ")}.` : "";
    const what = r.what.replace(/\.?$/, ".");
    const use = r.use.replace(/\.?$/, ".");
    md += `| [${r.repo}](https://github.com/${r.repo}) | ${r.verdict} | ${fmtStars(r.stars)} | ${r.risk}: ${cell(r.licText)} | ${cell(`${what} **Use:** ${use}${extra}`)} |\n`;
  }
}

const out = join(root, "REVIEW.md");
if (process.argv.includes("--check")) {
  const cur = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (cur !== md) { console.error("out of date: REVIEW.md"); process.exit(1); }
  console.log("review up to date");
} else {
  writeFileSync(out, md);
  console.log(`wrote REVIEW.md (${reviewed.length} entries)`, all);
}
